### ISSUE TITLE
Add All Motoko Examples

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/kybra#120]
Recreate all the examples in Dfinity's [examples](https://github.com/dfinity/examples/tree/master/motoko) repo. This should be the same as the motoko examples in Azle.

**Comment by bdemann** [comment]
This is essentially done. I remember that when we did it we were very eager to get it wrapped up and felt like we could have been a little more thorough in the code review. So we still need to go over all of the kybra motoko examples and make sure that they are all looking good.

**Comment by lastmjs** [comment]
This is not a priority anymore
