### ISSUE TITLE
Ensure that Kybra canisters are Candid discoverable

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/kybra#14]
For example, we want our canisters to be interacted with from websites like icscan.io. To achieve this, I think there are two paths. One is to have the Candid data stored automatically in the Wasm binary. Another I believe is the __get_temp_hack thing. Kybra already has __get_temp_hack. We may want to also or instead of that do the Candid service data stored in the binary.

Whatever we do, we should ensure the canisters are discoverable.

**Comment by bdemann** [comment]
Will be closed by #191
