### ISSUE TITLE
Consider adding __cdk_name

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/kybra#15]
It would be awesome to allow canister indexing tools to discover which CDK canisters were written in. This should be easily identifiable by doing something like the following in the Candid files:

```
type CDK = { kybra };
```

**Comment by lastmjs** [comment]
I think it's best to move forward with what is being discussed here: https://github.com/dfinity/motoko/issues/3462#issuecomment-1258599165

**Comment by bdemann** [comment]
Closed by #191
