### ISSUE TITLE
Custom types used only in system methods are not included in canister

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/kybra#152]
If we have a canister that uses a custom type only in a system method (init, pre-upgrade, post-upgrade, etc) and not in a regular canister method, then it doesn't get included in the final canister rust. The problem is in kybra/compiler/kybra_generate/src/py_ast/mod.rs:29. We only grab user-defined canister methods, meaning non-system methods.

**Comment by bdemann** [comment]
I think this was fixed in our new refactor since we aren't doing the dependency pass anymore. We just need to verify and create tests for this.

**Comment by dansteren** [comment]
This is confirmed to be working. I've added an example in https://github.com/demergent-labs/azle/pull/946.
