### ISSUE TITLE
Stable Structures

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/kybra#163]
Initial API design:

```python
from kybra import StableBTreeMap

stable_map: StableBTreeMap[str, str] = StableBTreeMap('stable_map', max_key_size=10, max_value_size=100)

```

**Comment by lastmjs** [comment]
Actually I think we need to do this:

```python
from kybra import StableBTreeMap
stable_map = StableBTreeMap[str, str]('stable_map', max_key_size=10, max_value_size=100)
```

**Comment by lastmjs** [comment]
```rust
pub struct StableBTreeMapNode {
    pub memory_id: u8,
    pub key_type: proc_macro2::TokenStream,
    pub value_type: proc_macro2::TokenStream,
    pub max_key_size: u32,
    pub max_value_size: u32,
}
```

**Comment by lastmjs** [comment]
Remaining items:

- [ ] Parsing for primitives
- [ ] Runtime for primitives
- [ ] Parsing for lists
- [ ] Runtime for lists
- [ ] Parsing for records
- [ ] Runtime for records
- [ ] Parsing for variants
- [ ] Runtime for variants

**Comment by lastmjs** [comment]
- [ ] new
- [ ] contains_key
- [ ] is_empty
- [ ] len
- [ ] remove
- [ ] iter/range

**Comment by lastmjs** [comment]
- [ ] Insert probably needs some work on the return type

**Comment by lastmjs** [comment]
- [ ] keys

**Comment by lastmjs** [comment]
- [ ] We need to add tests for keys, items, and entries??

**Comment by bdemann** [comment]
- [ ] Update example to match the API function names
