### ISSUE TITLE
Updated compiler errors

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/kybra#192]
The Kybra compiler errors should be as good as Azle's at least.

- [x] Address: https://github.com/demergent-labs/kybra/issues/192#issuecomment-1439262227
- [x] Address: https://github.com/demergent-labs/kybra/issues/192#issuecomment-1440449692

**Comment by bdemann** [comment]
Here are all of the todos and panics
- [ ] generators/
    - [ ] vm_value_conversion/try_into_vm_value/basic.rs
    - [ ] vm_value_conversion/try_from_vm_value/basic.rs
    - [ ] ic_object/functions/reply.rs
    - [ ] async_result_handler.rs (4)
- [ ] py_ast/kybra_types/
    - [ ] kybra_expr/
    - [ ] kybra_expr/errors.rs
    - [ ] kybra_stmt/data_types/records/record_members/errors.rs (2)
    - [ ] kybra_stmt/data_types/records/errors.rs
    - [ ] kybra_stmt/data_types/type_alias/mod.rs (2)
    - [ ] kybra_stmt/data_types/variants/variants_members/errors.rs (2)
    - [ ] kybra_stmt/data_types/variants/errors.rs
    - [ ] kybra_stmt/data_types/func/mod.rs (15)
    - [ ] kybra_stmt/canister_method.rs (5)
    - [ ] kybra_stmt/external_canisters/mod.rs (8)
    - [ ] kybra_stmt/system_methods/mod.rs
    - [ ] kybra_stmt/mod.rs
    - [ ] kybra_stmt/system_methods/errors.rs (2)
    - [ ] kybra_program/mod.rs
- [ ] py_ast/system_methods/
    - [ ] init.rs (2)
    - [ ] pre_upgrade.rs
    - [ ] inspect_message.rs
    - [ ] post_upgrade.rs (2)
    - [ ] heartbeat.rs (2)
- [ ] py_ast/
    - [ ] mod.rs

**Comment by bdemann** [comment]
```
thread 'main' panicked at 'error: Only Async, list, manual, opt, or tuple are allowed subscripts for candid values
  --> /home/bdemann/code/demergent_labs/kybra/examples/complex_types/src/state.py:12:16
   |
12 |       posts: dict[str, "StatePost"]
   |  ________________^
13 | |     reactions: dict[str, "StateReaction"]
   | |________^ Invalid subscript here
   |', src/py_ast/kybra_types/kybra_expr/to_act_data_type.rs:50:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This token size is messed up

**Comment by bdemann** [comment]
Closing in favor of https://github.com/demergent-labs/kybra/issues/198
