### ISSUE TITLE
func cannot have None as return value

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/kybra#235]
What we want to work:

```python

Callback: TypeAlias = Func(Update[[ModClubContentResult], None])
```

Error:

```
Error generating candid:
   Compiling kybra_generated_canister v0.0.0 (/Users/bob/Projects/Python Canisters/voting_reputation/.dfx/kybra/voting_reputation)
error: missing angle brackets in associated item path
    --> src/lib.rs:5766:26
     |
5766 |             rets: vec ! [(()) :: _ty ()],
     |                          ^^^^^^^^^^^ help: try: `<(())>::_ty`

error: could not compile `kybra_generated_canister` due to previous error

💀 Build failed
Error: Failed while trying to deploy canisters.
Caused by: Failed while trying to deploy canisters.
```

Tasks:

- [x] In Azle add a test to show that a return type of `null` works (and returns `null` in candid)
- [x] The Kybra tests should match the azle tests 100%
- [x] In Kybra `null` means `null` in candid, and `None` means `()` in candid.
- [x] Make sure that `None` isn't ever used in parameters.
- [x] Check that all examples use `None` and `null` correctly.
- [x] Make sure that Azle is actually working like this.

> **Note**
> The lack of a return type is not valid in Azle, but is valid in Kybra and means `None`

- [x] Make sure in Kybra doesn't use None for a type ever, and make sure we throw an error if anyone ever tries it.
- [x] Double check that azle is using void everywhere it should be an that no nulls are sneaking in.

**Comment by lastmjs** [comment]
I can imagine this not working in Azle as well

**Comment by bdemann** [comment]
All of the places we are using Func in Kybra examples are

func_types/src/notifiers/types.py
	NotifierFunc: TypeAlias = Func(Oneway[[blob], None])
func_types/src/func_types/main.py
	BasicFunc: TypeAlias = Func(Query[[str], str])
	ComplexFunc: TypeAlias = Func(Update[[User, Reaction], nat64])
	StableFunc: TypeAlias = Func(Query[[nat64, str], None])
list_of_lists/src/main.py
	BasicFunc: TypeAlias = Func(Query[[str], str])
motoko_examples/http_counter/src/main.py
	Callback: TypeAlias = Func(Query[[Token], StreamingCallbackHttpResponse])


The corrisponding Azle examples are

func_types/canisters/notifiers/types.ts
	export type NotifierFunc = Func<(message: blob) => Oneway>;
func_types/canisters/func_types/func_types.ts
	type BasicFunc = Func<(param1: string) => Query<string>>;
	type ComplexFunc = Func<(user: User, reaction: Reaction) => Update<nat64>>;
	type StableFunc = Func<(param1: nat64, param2: string) => Query<void>>;
list_of_lists/src/index.ts
	type BasicFunc = Func<(param1: string) => Query<string>>;
motoko_examples/http_counter/src/main.ts
	type Callback = Func<(t: Token) => Query<StreamingCallbackHttpResponse>>;

I added StableFunc so that it would match Azle so we should be good to go on that front.

**Comment by bdemann** [comment]
These are all of the files that have Nones that we need to look into

Needs fixing

- [ ] rejections/src/rejections/rejections.py
- [ ] cross_canister_calls/src/canister2/types.py

Questions

- [ ] optional_types/src/main.py
- [ ] outgoing_http_requests/src/main.py
- [ ] simple_user_accounts/src/main.py
- [ ] primitive_types/src/main.py
- [ ] bitcoin/src/main.py
- [ ] management_canister/src/management_canister.py
- [ ] func_types/src/notifiers/types.py
- [ ] stable_structures/src/canister2/stable_map_08.py
- [ ] manual_reply/src/main.py
- [ ] init/src/main.py

Opts

- [ ] motoko_examples/superheroes/src/main.py
- [ ] motoko_examples/calc/src/main.py
- [ ] motoko_examples/phone-book/src/main.py

Variants

- [ ] null_example/src/main.py
- [ ] principal/src/main.py
- [ ] tuple_types/src/main.py
- [ ] bitcoin/src/bitcoin_types.py
- [ ] examples/complex_types/src/candid_types.py
- [ ] stable_structures/src/canister1/stable_map_03.py
- [ ] stable_structures/src/canister2/stable_map_12.py
- [ ] keywords/src/main.py
- [ ] list_of_lists/src/main.py
- [ ] func_types/src/func_types/main.py

**Comment by bdemann** [comment]
Azle is ready to go https://github.com/demergent-labs/azle/pull/877

**Comment by bdemann** [comment]
Kybra is ready to go pending azle getting merged so we can use the same tests 
https://github.com/demergent-labs/kybra/pull/251
