### ISSUE TITLE
Ensure Inline types work everywhere

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/kybra#237]
Verify that inline types work everywhere including:

- [x] Canister method params
- [x] Canister method return types
- [x] StableBTreeMaps
- [x] External canister definitions
- [x] Vec, Opt, Func, Records and variants (and all permutations)
- [x] Address https://github.com/demergent-labs/kybra/issues/237#issuecomment-1398661312
- [x] Address https://github.com/demergent-labs/kybra/issues/237#issuecomment-1466986834
- [x] Funcs can now be inlined, ensure that they work

**Comment by bdemann** [comment]
Make sure the tuples are found recursively

**Comment by bdemann** [comment]
Add a simplified version of the inline_types example for kybra
