### ISSUE TITLE
typing stdlib is too large

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/kybra#36]
Until the IC increases its Wasm binary size limit, importing typing is just too much...I think because it imports all of the other libs to do its types? I am not sure...for now we might need to just pull from it what we need, and not allow the user to ever import it directly unfortunately. We should have the user import the types they need from kybra for now

**Comment by dansteren** [comment]
This will just be resolved once the Wasm binary limit is lifted. We're not doing more work on this at this time.
