### ISSUE TITLE
Dynamic Python module loading

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/kybra#39]
Perhaps we do not have to freeze our modules at all, maybe we can get a dynamic loader to work somehow...we could get a list of all modules required, maybe just a directory using our bundler, and then we just upload it like an asset canister. Then the files can be uploaded after deployment...no, this will be slow and complicated. I'm not sure this is the path we want to go down.

**Comment by dansteren** [comment]
Most likely, we should just wait for Dfinity to increase the Wasm binary limit.

**Comment by lastmjs** [comment]
Let's just wait for the Wasm binary limit to be lifted.
