### ISSUE TITLE
Fix encrypted identity issues

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/kybra#429]

**Comment by lastmjs** [comment]
I think we will simply make this trade-off for now. Kybra Beta does not allow you to use encrypted identities for the time being. dfx chunk uploading will hopefully allow us to remove the post_install process and thus get this functionality back.

**Comment by dansteren** [comment]
> [!Warning]
> Using encrypted identities can apparently cause huge memory usage.

Multiple users have tried to use encrypted identities and then run into issues in the post_install script when trying to clear chunks:

```rs
pub fn clear_chunks(canister_name: &str) -> Result<(), String> {
    let output = dfx("canister", "call", &vec![canister_name, "clear_chunks"])?;

    if !output.status.success() {
        return Err(create_error_string(&String::from_utf8_lossy(
            &output.stderr,
        )));
    }

    Ok(())
}
```

The first line of that function is the first dfx command the the script executes and the assumption is it waits to decrypt the identity and gets stuck here. We're not sure why this uses lots of ram, but WSL users will use up all the ram in their VM until the process just exits.

**Comment by dansteren** [comment]
One potential way to detect if they are using an identity would be to use a combination of `dfx identity whoami` and checking for the presence of a ` ~/.config/dfx/identity/THEIR_IDENTITY_NAME_HERE/identity.pem.encrypted` file.

**Comment by lastmjs** [comment]
dfx now supports larger Wasm binaries, and this issue is resolved
