### ISSUE TITLE
ic-wasm error installing due to older rust version used

### ISSUE THREAD

**Issue by Wizardwa** [demergent-labs/kybra#458]
In the __init__.py file the version of rust used which is 1.72.0 is obsolete as of Feb-2024. When deploying with dfx deploy, it is unable to install ic-wasm which requires an newer version of rustc to compile. 
Solution:
change __init__.py:21:__rust_version__ = "1.76.0"

**Comment by Dolphin1311** [comment]
The same issue too

**Comment by Wizardwa** [comment]
Have been able to solve the issue

**Comment by lastmjs** [comment]
This problem should be fixed if you are using version 0.5.3 of Kybra, please let me know if you are using 0.5.3 and are still experiencing the issue.

https://github.com/demergent-labs/kybra/releases/tag/0.5.3
